### PR TITLE
Fix for an issue: https://wordpress.org/support/topic/add-respond-id-…

### PR DESCRIPTION
**Pull request by Crunchify**
…to-disqus-comment-form?replies=1

### CODE REVIEW

**Comment by joel-james** [comment]
@Crunchify Thanks. Will merge this soon.

**Comment by joel-james** [comment]
This may make conflicts with some themes. I have implemented another method. Please update the plugin and check. Let me know after that.

**Comment by Crunchify** [comment]
Hi Joel - is this fixed? Seems it's not working on site http://crunchify.com

**Comment by joel-james** [comment]
Hi @Crunchify 

Yes. I have added a fix. But in your case I think your theme hooks into the `respond_link()` filter with low priority. Can you download master branch from this GitHub repo and check? I will update the wp.org plugin after confirmation.

**Comment by Crunchify** [comment]
Just tried. Still same result.

image

**Comment by joel-james** [comment]
Hi Crunchify,

Ok, I will look into this. Will update you next week.

**Comment by Crunchify** [comment]
Ack. Thanks.

**Comment by joel-james** [comment]
Btw, full code revamp coming soon :tada:

**Comment by Crunchify** [comment]
Hi  Joel - any update?

**Comment by Joel-James** [comment]
Hi @Crunchify,

I'm sorry. On a busy schedule right now :racehorse: Will work on this, coming weekend.

**Pull request closed without merging**
